import { generateDeals } from "@/lib/generate-deals";
import type { PipelineDeal } from "@/lib/deal-types";

export type { DealStage, ReadinessStatus, PipelineDeal } from "@/lib/deal-types";

function featured(partial: Omit<PipelineDeal, "hasFullWorkflow">): PipelineDeal {
  return { ...partial, hasFullWorkflow: true };
}

/** Hand-curated demo deals — always present regardless of generated set size. */
const featuredDeals: PipelineDeal[] = [
  featured({
    id: "northwind-logistics",
    name: "Northwind Logistics",
    tagline: "AI-powered last-mile delivery optimization",
    description:
      "Northwind builds an ML routing layer for mid-market shippers, improving delivery density and reducing cost per stop versus legacy TMS add-ons.",
    categoryId: "enterprise-software",
    sector: "Enterprise Software",
    stage: "ic_prep",
    owner: "Alex Rivera",
    arr: "$12.0M",
    growth: "+28% YoY",
    askAmount: "$45M Series B",
    location: "Chicago, IL",
    founded: "2019",
    employees: "85",
    readinessScore: 4,
    readinessStatus: "blocked",
    conflictCount: 2,
    openItems: 6,
    documentsReviewed: 6,
    lastUpdated: "2 min ago",
    dateAdded: 0,
    tags: ["Growth Equity", "North America", "SaaS"],
    highlights: [
      "Multi-year contracts with two anchor enterprise customers",
      "API-first architecture with documented WMS connectors",
    ],
  }),
  featured({
    id: "helix-health",
    name: "Helix Health Ops",
    tagline: "Prior authorization automation for hospital systems",
    description: "Helix automates prior auth workflows for mid-size hospital networks.",
    categoryId: "healthcare",
    sector: "Healthcare IT",
    stage: "diligence",
    owner: "Alex Rivera",
    arr: "$8.4M",
    growth: "+42% YoY",
    askAmount: "$30M Series B",
    location: "Boston, MA",
    founded: "2020",
    employees: "62",
    readinessScore: 6,
    readinessStatus: "in_review",
    conflictCount: 0,
    openItems: 9,
    documentsReviewed: 4,
    lastUpdated: "1 hr ago",
    dateAdded: 2,
    tags: ["Healthcare", "Series B"],
    highlights: ["Live with 12 hospital systems", "HIPAA-compliant infrastructure"],
  }),
  featured({
    id: "stonegate-properties",
    name: "Stonegate Properties",
    tagline: "Operating system for multifamily asset managers",
    description: "Stonegate unifies leasing, maintenance, and investor reporting for mid-market portfolios.",
    categoryId: "real-estate",
    sector: "PropTech",
    stage: "diligence",
    owner: "Jordan Lee",
    arr: "$8.4M",
    growth: "+35% YoY",
    askAmount: "$25M Series B",
    location: "Denver, CO",
    founded: "2018",
    employees: "48",
    readinessScore: 5,
    readinessStatus: "in_review",
    conflictCount: 1,
    openItems: 7,
    documentsReviewed: 5,
    lastUpdated: "1 hr ago",
    dateAdded: 3,
    tags: ["PropTech", "Series B"],
    highlights: ["120+ properties under management", "Strong NOI uplift in pilot markets"],
  }),
  featured({
    id: "meridian-analytics",
    name: "Meridian Analytics",
    tagline: "Semantic layer for modern data stacks",
    description: "Meridian gives analytics teams a governed semantic layer above Snowflake and dbt.",
    categoryId: "enterprise-software",
    sector: "Data Infrastructure",
    stage: "diligence",
    owner: "Sam Chen",
    arr: "$5.6M",
    growth: "+48% YoY",
    askAmount: "$40M Series B",
    location: "San Francisco, CA",
    founded: "2021",
    employees: "74",
    readinessScore: 6,
    readinessStatus: "in_review",
    conflictCount: 0,
    openItems: 2,
    documentsReviewed: 7,
    lastUpdated: "2 hr ago",
    dateAdded: 1,
    tags: ["Enterprise Software", "Series B"],
    highlights: ["Deployed at 40+ accounts", "Strong expansion within data teams"],
  }),
  featured({
    id: "cascade-payments",
    name: "Cascade Payments",
    tagline: "Embedded B2B payments for vertical SaaS",
    description: "Cascade provides white-label payment rails and reconciliation for industry software platforms.",
    categoryId: "fintech",
    sector: "Fintech",
    stage: "diligence",
    owner: "Alex Rivera",
    arr: "$9.8M",
    growth: "+52% YoY",
    askAmount: "$35M Series B",
    location: "New York, NY",
    founded: "2019",
    employees: "56",
    readinessScore: 7,
    readinessStatus: "in_review",
    conflictCount: 0,
    openItems: 5,
    documentsReviewed: 5,
    lastUpdated: "6 hr ago",
    dateAdded: 4,
    tags: ["Fintech", "Embedded finance"],
    highlights: ["Processing $1.2B annualized volume", "Net revenue retention above 115%"],
  }),
  featured({
    id: "vault-realty-capital",
    name: "Vault Realty Capital",
    tagline: "Debt marketplace for commercial real estate sponsors",
    description: "Vault connects CRE sponsors with regional lenders through a standardized underwriting workflow.",
    categoryId: "real-estate",
    sector: "Real Estate Finance",
    stage: "diligence",
    owner: "Jordan Lee",
    arr: "$15.2M",
    growth: "+31% YoY",
    askAmount: "$20M Series A",
    location: "Miami, FL",
    founded: "2020",
    employees: "38",
    readinessScore: 7,
    readinessStatus: "in_review",
    conflictCount: 1,
    openItems: 4,
    documentsReviewed: 6,
    lastUpdated: "25 min ago",
    dateAdded: 5,
    tags: ["Real Estate", "Marketplace"],
    highlights: ["$800M loan requests facilitated", "Repeat sponsor rate above 60%"],
  }),
  featured({
    id: "clearbank-systems",
    name: "Clear Bank Systems",
    tagline: "Core banking modernization for regional banks",
    description: "Clear Bank helps community banks migrate deposit and lending workflows to a modular cloud core.",
    categoryId: "fintech",
    sector: "Banking Infrastructure",
    stage: "diligence",
    owner: "Sam Chen",
    arr: "$11.3M",
    growth: "+24% YoY",
    askAmount: "$50M Series B",
    location: "Charlotte, NC",
    founded: "2017",
    employees: "92",
    readinessScore: 7,
    readinessStatus: "in_review",
    conflictCount: 0,
    openItems: 3,
    documentsReviewed: 8,
    lastUpdated: "8 hr ago",
    dateAdded: 6,
    tags: ["Fintech", "Regulated"],
    highlights: ["Three live bank migrations", "SOC 2 Type II certified"],
  }),
  featured({
    id: "brightcart",
    name: "Bright Cart",
    tagline: "Checkout infrastructure for mid-market retailers",
    description: "Bright Cart powers unified checkout, loyalty, and returns for omnichannel retail brands.",
    categoryId: "consumer",
    sector: "Retail Tech",
    stage: "diligence",
    owner: "Sam Chen",
    arr: "$2.7M",
    growth: "+38% YoY",
    askAmount: "$28M Series B",
    location: "Austin, TX",
    founded: "2019",
    employees: "51",
    readinessScore: 9,
    readinessStatus: "ready",
    conflictCount: 0,
    openItems: 6,
    documentsReviewed: 4,
    lastUpdated: "3 hr ago",
    dateAdded: 7,
    tags: ["Consumer", "Retail"],
    highlights: ["GMV $420M on platform", "Top-20 retailer pilots in progress"],
  }),
  featured({
    id: "lumen-home",
    name: "Lumen Home",
    tagline: "Smart home energy management for utilities",
    description: "Lumen partners with utilities to deploy demand-response and home energy optimization at scale.",
    categoryId: "consumer",
    sector: "Climate Tech",
    stage: "diligence",
    owner: "Jordan Lee",
    arr: "$5.9M",
    growth: "+44% YoY",
    askAmount: "$22M Series A",
    location: "Seattle, WA",
    founded: "2021",
    employees: "44",
    readinessScore: 4,
    readinessStatus: "blocked",
    conflictCount: 1,
    openItems: 8,
    documentsReviewed: 3,
    lastUpdated: "3 hr ago",
    dateAdded: 8,
    tags: ["Climate", "Consumer"],
    highlights: ["Utility partnerships in 4 states", "Strong pilot retention metrics"],
  }),
  featured({
    id: "atlas-logic",
    name: "Atlas Logic",
    tagline: "Workflow automation for insurance operations",
    description: "Atlas automates claims intake, routing, and compliance checks for regional P&C carriers.",
    categoryId: "enterprise-software",
    sector: "InsurTech",
    stage: "ic_prep",
    owner: "Sam Chen",
    arr: "$10.2M",
    growth: "+33% YoY",
    askAmount: "$32M Series B",
    location: "Chicago, IL",
    founded: "2018",
    employees: "67",
    readinessScore: 6,
    readinessStatus: "blocked",
    conflictCount: 1,
    openItems: 5,
    documentsReviewed: 6,
    lastUpdated: "1 hr ago",
    dateAdded: 9,
    tags: ["InsurTech", "Enterprise"],
    highlights: ["Claims cycle time reduced 40%", "Multi-carrier deployments"],
  }),
];

const GENERATED_COUNT = 990;

export const pipelineDeals: PipelineDeal[] = [
  ...featuredDeals,
  ...generateDeals(GENERATED_COUNT),
];

export function getDealById(id: string): PipelineDeal | undefined {
  return pipelineDeals.find((d) => d.id === id);
}

export function getDealsByCategory(categoryId: string): PipelineDeal[] {
  if (categoryId === "all") return pipelineDeals;
  return pipelineDeals.filter((d) => d.categoryId === categoryId);
}

export const pipelineStats = {
  total: pipelineDeals.length,
  owners: [...new Set(pipelineDeals.map((d) => d.owner))].sort(),
};
