import { buildExportArchiveHtml, downloadExportArchivePdf, downloadExportArchiveWord } from "@/lib/export-document";
import type { ExportHistoryItem } from "@/lib/exports-mock";

export { buildExportArchiveHtml, downloadExportArchivePdf, downloadExportArchiveWord };

/** @deprecated Use downloadExportArchivePdf — kept for tests and markdown fallback. */
export function buildExportArchiveMarkdown(item: ExportHistoryItem): string {
  const exportedDate = item.exportedAt.split(" ")[0] ?? item.exportedAt;

  return `# IC Package — ${item.company}
**Exported:** ${exportedDate}  
**Decision:** ${item.decision.toUpperCase()}  
**Rationale:** ${item.rationalePreview}  
**Prepared by:** ${item.owner}  
**Readiness score at export:** ${item.readiness}  
**Open issues at download:** ${item.blockersAtExport}

---

## Decision record

This package was exported from ICReady after a human sign-off. The AI prepared diligence materials; the associate or partner recorded the final decision above.

## Archive note

This is a compliance archive copy. Source contradictions, checklist items, and one-pager content from the original export session are retained in the ICReady audit trail.

---

*Generated by ICReady AI. Human decision recorded before export.*
`;
}

export function downloadExportArchive(item: ExportHistoryItem): void {
  downloadExportArchivePdf(item);
}

export function matchesExportSearch(item: ExportHistoryItem, query: string): boolean {
  const q = query.trim().toLowerCase();
  if (!q) return true;
  return (
    item.company.toLowerCase().includes(q) ||
    item.owner.toLowerCase().includes(q) ||
    item.rationalePreview.toLowerCase().includes(q) ||
    item.decision.toLowerCase().includes(q)
  );
}
