import type { AnalysisResult } from "./types";

export const northwindAnalysis: AnalysisResult = {
  deal: {
    id: "northwind-logistics",
    name: "Northwind Logistics",
    description:
      "Provider of AI-powered last-mile delivery optimization solutions for mid-market shippers",
    tags: ["Growth Equity", "Enterprise Software", "North America"],
    owner: "Alex Rivera",
    source: "Google Sheet · Deal Pipeline",
    lastUpdated: "2 min ago",
  },
  sourcesReviewed: ["Google Sheet", "Investor memo", "Founder notes", "Uploaded PDF"],
  onePager: {
    thesis:
      "Northwind offers a differentiated AI routing layer for mid-market shippers, improving delivery density and reducing cost per stop versus legacy TMS add-ons.",
    whyNow:
      "Carrier rate volatility and same-day delivery expectations are forcing shippers to optimize routes weekly, not quarterly. Incumbent TMS vendors lack real-time ML re-optimization.",
    keyRisks: [
      "Revenue growth may be slower than pipeline suggests",
      "Customer concentration in top 3 accounts",
      "Integration complexity with legacy WMS stacks",
    ],
    mitigants: [
      "Multi-year contracts with two anchor customers",
      "API-first architecture with documented connectors",
      "Strong product roadmap for WMS integrations in H2",
    ],
  },
  readinessScore: 6,
  openQuestions: 7,
  documentsReviewed: 6,
  sourceCount: 4,
  diligenceProgress: 54,
  blockingConflictCount: 2,
  analyzedAt: new Date().toISOString(),
  usedLiveAI: false,
  verdictBlockers: [
    "2 financial numbers still don't match",
    "4 research tasks still open",
    "2 claims still lack proof",
  ],
  keyFacts: [
    {
      label: "ARR",
      value: "$12.0M claimed",
      confidence: "low",
      sources: "Google Sheet vs memo conflict",
      note: "Source conflict detected",
    },
    {
      label: "Growth",
      value: "+28% YoY claimed",
      confidence: "low",
      sources: "Sheet shows +28%; memo states flat YoY",
    },
    {
      label: "Employees",
      value: "85",
      confidence: "high",
      sources: "Memo + company profile",
    },
  ],
  contradictions: [
    {
      id: "c1",
      field: "ARR (2024)",
      sourceA: {
        name: "Google Sheet",
        value: "$12.0M",
        quote: "Row 14: ARR (2024) = $12.0M, growth +28% YoY",
      },
      sourceB: {
        name: "Investor memo",
        value: "$9.0M",
        quote: "Section 2: FY24 ARR approximately $9M, flat YoY",
      },
      severity: "high",
      suggestedAction: "Get updated financials and align annual revenue with the finance team",
      whyItMatters: "Annual revenue drives how we value the company and its growth story.",
      whyItBlocksIC: "The committee needs one agreed annual revenue number before recommending the deal.",
      status: "unresolved",
      linkedChecklistId: "cl1",
    },
    {
      id: "c2",
      field: "Customer concentration",
      sourceA: {
        name: "Google Sheet",
        value: "Top 3 = 42% revenue",
        quote: "Pipeline tab: concentration flagged as moderate",
      },
      sourceB: {
        name: "CIM Extract",
        value: "Top 3 = 68% revenue",
        quote: "Appendix B: largest three customers represent 68% of FY24 revenue",
      },
      severity: "high",
      suggestedAction: "Confirm top-customer revenue using audited files from the data room",
      whyItMatters: "Too much revenue from a few customers increases risk if one leaves.",
      whyItBlocksIC: "The committee needs a clear picture of top customers before sizing the investment.",
      status: "unresolved",
      linkedChecklistId: "cl2",
    },
    {
      id: "c3",
      field: "Gross margin",
      sourceA: {
        name: "Investor memo",
        value: "72%",
        quote: "Blended gross margin of 72% post hosting optimization",
      },
      sourceB: {
        name: "Financial Model",
        value: "64%",
        quote: "Model tab P&L: GM 64% in base case",
      },
      severity: "medium",
      suggestedAction: "Get an updated financial model or confirmation from the finance team",
      whyItMatters: "Profit margin shows how efficiently the business makes money.",
      whyItBlocksIC: "The committee needs one agreed profit margin before trusting the financial story.",
      status: "unresolved",
      linkedChecklistId: "cl5",
    },
  ],
  unsupportedClaims: [
    {
      id: "nw-uc1",
      claim: "Strong retention in core enterprise segment",
      source: "AI draft / memo",
      evidenceStatus: "not_supported",
      requiredProof: "NDR cohort table",
    },
    {
      id: "nw-uc2",
      claim: "Expanding go-to-market motion with improving unit economics",
      source: "Founder notes",
      evidenceStatus: "partially_supported",
      requiredProof: "Sales pipeline or CAC trend",
    },
    {
      id: "nw-uc3",
      claim: "Last-mile spend is shifting toward automation at scale",
      source: "AI draft",
      evidenceStatus: "needs_source",
      requiredProof: "Market report or customer budget evidence",
    },
  ],
  checklist: [
    {
      id: "cl1",
      label: "Reconcile revenue and margin figures",
      priority: "high",
      linkedRisk: "Financial conflict",
      linkedIssue: "ARR mismatch",
      owner: "Alex Rivera",
      done: false,
    },
    {
      id: "cl2",
      label: "Customer reference calls (top 3 accounts)",
      priority: "high",
      linkedRisk: "Customer concentration",
      linkedIssue: "Customer concentration",
      owner: "Alex Rivera",
      done: false,
    },
    {
      id: "cl3",
      label: "Legal review of customer contracts",
      priority: "high",
      linkedRisk: "Contract terms / churn",
      linkedIssue: "Governance",
      owner: "Legal",
      done: false,
    },
    {
      id: "cl4",
      label: "Technical diligence on WMS integrations",
      priority: "medium",
      linkedRisk: "Integration complexity",
      linkedIssue: "Product risk",
      owner: "Alex Rivera",
      done: false,
    },
    {
      id: "cl5",
      label: "Retention & cohort analysis",
      priority: "medium",
      linkedRisk: "Gross margin variance",
      linkedIssue: "Gross margin conflict",
      owner: "Alex Rivera",
      done: false,
    },
    {
      id: "cl6",
      label: "Cap table & option pool review",
      priority: "low",
      linkedRisk: "Governance",
      linkedIssue: "Governance",
      owner: "Legal",
      done: true,
    },
  ],
  packageSections: [
    { id: "overview", section: "Company overview", status: "ready" },
    { id: "market", section: "Market story", status: "needs_support", blocker: "Missing market research" },
    { id: "financial", section: "Financial summary", status: "blocked", blocker: "Financial numbers don't match" },
    { id: "customer", section: "Customer research", status: "blocked", blocker: "Customer calls not done" },
    { id: "risks", section: "Risks & responses", status: "draft_ready", blocker: "Check sources" },
    { id: "recommendation", section: "Your recommendation", status: "not_started", blocker: "Decision needed" },
  ],
  auditTrail: [
    {
      id: "nw-a1",
      timestamp: new Date().toISOString(),
      label: "AI finished reviewing the documents",
      type: "ai",
    },
    {
      id: "nw-a2",
      timestamp: new Date().toISOString(),
      label: "Mismatch found: annual revenue",
      type: "warning",
    },
    {
      id: "nw-a3",
      timestamp: new Date().toISOString(),
      label: "Mismatch found: customer concentration",
      type: "warning",
    },
    {
      id: "nw-a4",
      timestamp: new Date().toISOString(),
      label: "Draft summary created",
      type: "ai",
    },
    {
      id: "nw-a5",
      timestamp: new Date().toISOString(),
      label: "Waiting for your decision",
      type: "human",
    },
  ],
};

export const mockSheetRow = {
  company: "Northwind Logistics",
  arr2024: "$12.0M",
  growth: "+28% YoY",
  concentration: "Top 3 = 42%",
  stage: "Series B",
  owner: "Alex Rivera",
};
