/**
 * Pre-extracted portfolio metrics from demo PDFs — types, sample reports,
 * metric catalog, and normalized extraction records from the Python POC.
 */

export type PortfolioMetric = {
  company: string;
  reportingPeriod: string | null;
  metricKey: string;
  metricName: string;
  category: "financial" | "operating";
  rawValue: string;
  normalizedValue: number;
  unit: string;
  confidence: number;
  extractionMethod: "inline_label" | "table_row" | "narrative_prose";
  sourcePage: number;
  sourceSnippet: string;
  sourceFile: string;
};

export type SampleReport = {
  id: string;
  fileName: string;
  company: string;
  period: string;
  layout: string;
};

/** Pre-extracted from the Python POC (`sagard-portfolio-metrics`). */
export const SAMPLE_REPORTS: SampleReport[] = [
  {
    id: "northwind",
    fileName: "Northwind_Logistics_Q4_2025_Board_Pack.pdf",
    company: "Northwind Logistics",
    period: "Q4 2025",
    layout: "Inline board pack",
  },
  {
    id: "helix",
    fileName: "Helix_Health_FY2025_Investor_Update.pdf",
    company: "Helix Health",
    period: "FY 2025",
    layout: "Metrics table",
  },
  {
    id: "meridian",
    fileName: "Meridian_Analytics_Dec_2025_Monthly_Report.pdf",
    company: "Meridian Analytics",
    period: "Dec 2025",
    layout: "Split label / value",
  },
  {
    id: "cascade",
    fileName: "Cascade_Payments_Q3_2025_Operating_Review.pdf",
    company: "Cascade Payments",
    period: "Q3 2025",
    layout: "Narrative prose",
  },
];

export const PORTFOLIO_METRICS: PortfolioMetric[] = [
  {
    company: "Cascade Payments",
    reportingPeriod: "Q3 2025",
    metricKey: "arr",
    metricName: "ARR",
    category: "operating",
    rawValue: "$27.5M",
    normalizedValue: 27500000,
    unit: "USD",
    confidence: 0.82,
    extractionMethod: "narrative_prose",
    sourcePage: 1,
    sourceSnippet: "Management reported ARR of 27.5M, gross margin of 54.6 percent…",
    sourceFile: "Cascade_Payments_Q3_2025_Operating_Review.pdf",
  },
  {
    company: "Cascade Payments",
    reportingPeriod: "Q3 2025",
    metricKey: "cash",
    metricName: "Cash balance",
    category: "financial",
    rawValue: "$8.9m",
    normalizedValue: 8900000,
    unit: "USD",
    confidence: 0.82,
    extractionMethod: "narrative_prose",
    sourcePage: 1,
    sourceSnippet: "…ending cash of $8.9 million.",
    sourceFile: "Cascade_Payments_Q3_2025_Operating_Review.pdf",
  },
  {
    company: "Cascade Payments",
    reportingPeriod: "Q3 2025",
    metricKey: "churn",
    metricName: "Logo churn",
    category: "operating",
    rawValue: "1.8%",
    normalizedValue: 1.8,
    unit: "percent",
    confidence: 0.98,
    extractionMethod: "inline_label",
    sourcePage: 1,
    sourceSnippet: "Monthly churn - 1.8%",
    sourceFile: "Cascade_Payments_Q3_2025_Operating_Review.pdf",
  },
  {
    company: "Cascade Payments",
    reportingPeriod: "Q3 2025",
    metricKey: "ebitda",
    metricName: "EBITDA",
    category: "financial",
    rawValue: "$3.6M",
    normalizedValue: 3600000,
    unit: "USD",
    confidence: 0.98,
    extractionMethod: "inline_label",
    sourcePage: 1,
    sourceSnippet: "EBITDA - $3.6M",
    sourceFile: "Cascade_Payments_Q3_2025_Operating_Review.pdf",
  },
  {
    company: "Cascade Payments",
    reportingPeriod: "Q3 2025",
    metricKey: "gross_margin",
    metricName: "Gross margin",
    category: "financial",
    rawValue: "54.6%",
    normalizedValue: 54.6,
    unit: "percent",
    confidence: 0.82,
    extractionMethod: "narrative_prose",
    sourcePage: 1,
    sourceSnippet: "…gross margin of 54.6 percent…",
    sourceFile: "Cascade_Payments_Q3_2025_Operating_Review.pdf",
  },
  {
    company: "Cascade Payments",
    reportingPeriod: "Q3 2025",
    metricKey: "headcount",
    metricName: "Headcount",
    category: "operating",
    rawValue: "211",
    normalizedValue: 211,
    unit: "count",
    confidence: 0.98,
    extractionMethod: "inline_label",
    sourcePage: 1,
    sourceSnippet: "Headcount - 211",
    sourceFile: "Cascade_Payments_Q3_2025_Operating_Review.pdf",
  },
  {
    company: "Cascade Payments",
    reportingPeriod: "Q3 2025",
    metricKey: "nrr",
    metricName: "Net revenue retention",
    category: "operating",
    rawValue: "115%",
    normalizedValue: 115,
    unit: "percent",
    confidence: 0.98,
    extractionMethod: "inline_label",
    sourcePage: 1,
    sourceSnippet: "Net Dollar Retention - 115%",
    sourceFile: "Cascade_Payments_Q3_2025_Operating_Review.pdf",
  },
  {
    company: "Cascade Payments",
    reportingPeriod: "Q3 2025",
    metricKey: "pipeline",
    metricName: "Sales pipeline",
    category: "operating",
    rawValue: "$14.2M",
    normalizedValue: 14200000,
    unit: "USD",
    confidence: 0.98,
    extractionMethod: "inline_label",
    sourcePage: 1,
    sourceSnippet: "Qualified Pipeline: $14.2M",
    sourceFile: "Cascade_Payments_Q3_2025_Operating_Review.pdf",
  },
  {
    company: "Cascade Payments",
    reportingPeriod: "Q3 2025",
    metricKey: "revenue",
    metricName: "Revenue",
    category: "financial",
    rawValue: "$24.8m",
    normalizedValue: 24800000,
    unit: "USD",
    confidence: 0.82,
    extractionMethod: "narrative_prose",
    sourcePage: 1,
    sourceSnippet: "Cascade grew net revenue to USD 24.8 million during the quarter…",
    sourceFile: "Cascade_Payments_Q3_2025_Operating_Review.pdf",
  },
  {
    company: "Helix Health",
    reportingPeriod: "2025",
    metricKey: "arr",
    metricName: "ARR",
    category: "operating",
    rawValue: "$31.2M",
    normalizedValue: 31200000,
    unit: "USD",
    confidence: 0.9,
    extractionMethod: "table_row",
    sourcePage: 1,
    sourceSnippet: "Annual Recurring Revenue $31.2M",
    sourceFile: "Helix_Health_FY2025_Investor_Update.pdf",
  },
  {
    company: "Helix Health",
    reportingPeriod: "2025",
    metricKey: "cash",
    metricName: "Cash balance",
    category: "financial",
    rawValue: "$22.7M",
    normalizedValue: 22700000,
    unit: "USD",
    confidence: 0.9,
    extractionMethod: "table_row",
    sourcePage: 1,
    sourceSnippet: "Ending Cash $22.7M",
    sourceFile: "Helix_Health_FY2025_Investor_Update.pdf",
  },
  {
    company: "Helix Health",
    reportingPeriod: "2025",
    metricKey: "churn",
    metricName: "Logo churn",
    category: "operating",
    rawValue: "3.4%",
    normalizedValue: 3.4,
    unit: "percent",
    confidence: 0.9,
    extractionMethod: "table_row",
    sourcePage: 1,
    sourceSnippet: "Customer Churn 3.4%",
    sourceFile: "Helix_Health_FY2025_Investor_Update.pdf",
  },
  {
    company: "Helix Health",
    reportingPeriod: "2025",
    metricKey: "ebitda",
    metricName: "EBITDA",
    category: "financial",
    rawValue: "$4.1M",
    normalizedValue: 4100000,
    unit: "USD",
    confidence: 0.9,
    extractionMethod: "table_row",
    sourcePage: 1,
    sourceSnippet: "Adj. EBITDA $4.1M",
    sourceFile: "Helix_Health_FY2025_Investor_Update.pdf",
  },
  {
    company: "Helix Health",
    reportingPeriod: "2025",
    metricKey: "gross_margin",
    metricName: "Gross margin",
    category: "financial",
    rawValue: "72.8%",
    normalizedValue: 72.8,
    unit: "percent",
    confidence: 0.9,
    extractionMethod: "table_row",
    sourcePage: 1,
    sourceSnippet: "Gross Margin % 72.8%",
    sourceFile: "Helix_Health_FY2025_Investor_Update.pdf",
  },
  {
    company: "Helix Health",
    reportingPeriod: "2025",
    metricKey: "headcount",
    metricName: "Headcount",
    category: "operating",
    rawValue: "164",
    normalizedValue: 164,
    unit: "count",
    confidence: 0.9,
    extractionMethod: "table_row",
    sourcePage: 1,
    sourceSnippet: "Employees 164",
    sourceFile: "Helix_Health_FY2025_Investor_Update.pdf",
  },
  {
    company: "Helix Health",
    reportingPeriod: "2025",
    metricKey: "nrr",
    metricName: "Net revenue retention",
    category: "operating",
    rawValue: "108%",
    normalizedValue: 108,
    unit: "percent",
    confidence: 0.9,
    extractionMethod: "table_row",
    sourcePage: 1,
    sourceSnippet: "NRR 108%",
    sourceFile: "Helix_Health_FY2025_Investor_Update.pdf",
  },
  {
    company: "Helix Health",
    reportingPeriod: "2025",
    metricKey: "pipeline",
    metricName: "Sales pipeline",
    category: "operating",
    rawValue: "$11.8M",
    normalizedValue: 11800000,
    unit: "USD",
    confidence: 0.98,
    extractionMethod: "inline_label",
    sourcePage: 1,
    sourceSnippet: "Sales pipeline | $11.8M",
    sourceFile: "Helix_Health_FY2025_Investor_Update.pdf",
  },
  {
    company: "Helix Health",
    reportingPeriod: "2025",
    metricKey: "revenue",
    metricName: "Revenue",
    category: "financial",
    rawValue: "$28.4M",
    normalizedValue: 28400000,
    unit: "USD",
    confidence: 0.9,
    extractionMethod: "table_row",
    sourcePage: 1,
    sourceSnippet: "Net Revenue $28.4M",
    sourceFile: "Helix_Health_FY2025_Investor_Update.pdf",
  },
  {
    company: "Meridian Analytics",
    reportingPeriod: "DEC",
    metricKey: "arr",
    metricName: "ARR",
    category: "operating",
    rawValue: "$19.1M",
    normalizedValue: 19100000,
    unit: "USD",
    confidence: 0.9,
    extractionMethod: "table_row",
    sourcePage: 1,
    sourceSnippet: "Annualized Recurring Revenue $19.1M",
    sourceFile: "Meridian_Analytics_Dec_2025_Monthly_Report.pdf",
  },
  {
    company: "Meridian Analytics",
    reportingPeriod: "DEC",
    metricKey: "cash",
    metricName: "Cash balance",
    category: "financial",
    rawValue: "$6.4M",
    normalizedValue: 6400000,
    unit: "USD",
    confidence: 0.9,
    extractionMethod: "table_row",
    sourcePage: 1,
    sourceSnippet: "Cash Balance $6.4M",
    sourceFile: "Meridian_Analytics_Dec_2025_Monthly_Report.pdf",
  },
  {
    company: "Meridian Analytics",
    reportingPeriod: "DEC",
    metricKey: "ebitda",
    metricName: "EBITDA",
    category: "financial",
    rawValue: "$2.3M",
    normalizedValue: 2300000,
    unit: "USD",
    confidence: 0.9,
    extractionMethod: "table_row",
    sourcePage: 1,
    sourceSnippet: "EBITDA $2.3M",
    sourceFile: "Meridian_Analytics_Dec_2025_Monthly_Report.pdf",
  },
  {
    company: "Meridian Analytics",
    reportingPeriod: "DEC",
    metricKey: "gross_margin",
    metricName: "Gross margin",
    category: "financial",
    rawValue: "58.2%",
    normalizedValue: 58.2,
    unit: "percent",
    confidence: 0.9,
    extractionMethod: "table_row",
    sourcePage: 1,
    sourceSnippet: "GM 58.2%",
    sourceFile: "Meridian_Analytics_Dec_2025_Monthly_Report.pdf",
  },
  {
    company: "Meridian Analytics",
    reportingPeriod: "DEC",
    metricKey: "headcount",
    metricName: "Headcount",
    category: "operating",
    rawValue: "97 employees",
    normalizedValue: 97,
    unit: "count",
    confidence: 0.9,
    extractionMethod: "table_row",
    sourcePage: 1,
    sourceSnippet: "Team Size 97 employees",
    sourceFile: "Meridian_Analytics_Dec_2025_Monthly_Report.pdf",
  },
  {
    company: "Meridian Analytics",
    reportingPeriod: "DEC",
    metricKey: "revenue",
    metricName: "Revenue",
    category: "financial",
    rawValue: "$17.6M",
    normalizedValue: 17600000,
    unit: "USD",
    confidence: 0.9,
    extractionMethod: "table_row",
    sourcePage: 1,
    sourceSnippet: "Total Revenue $17.6M",
    sourceFile: "Meridian_Analytics_Dec_2025_Monthly_Report.pdf",
  },
  {
    company: "Northwind Logistics",
    reportingPeriod: "Q4 2025",
    metricKey: "arr",
    metricName: "ARR",
    category: "operating",
    rawValue: "$52.6M",
    normalizedValue: 52600000,
    unit: "USD",
    confidence: 0.98,
    extractionMethod: "inline_label",
    sourcePage: 1,
    sourceSnippet: "ARR: $52.6M",
    sourceFile: "Northwind_Logistics_Q4_2025_Board_Pack.pdf",
  },
  {
    company: "Northwind Logistics",
    reportingPeriod: "Q4 2025",
    metricKey: "cash",
    metricName: "Cash balance",
    category: "financial",
    rawValue: "$14.3M",
    normalizedValue: 14300000,
    unit: "USD",
    confidence: 0.98,
    extractionMethod: "inline_label",
    sourcePage: 1,
    sourceSnippet: "Cash on hand: $14.3M",
    sourceFile: "Northwind_Logistics_Q4_2025_Board_Pack.pdf",
  },
  {
    company: "Northwind Logistics",
    reportingPeriod: "Q4 2025",
    metricKey: "churn",
    metricName: "Logo churn",
    category: "operating",
    rawValue: "2.1%",
    normalizedValue: 2.1,
    unit: "percent",
    confidence: 0.98,
    extractionMethod: "inline_label",
    sourcePage: 1,
    sourceSnippet: "Logo churn: 2.1%",
    sourceFile: "Northwind_Logistics_Q4_2025_Board_Pack.pdf",
  },
  {
    company: "Northwind Logistics",
    reportingPeriod: "Q4 2025",
    metricKey: "ebitda",
    metricName: "EBITDA",
    category: "financial",
    rawValue: "$9.8M",
    normalizedValue: 9800000,
    unit: "USD",
    confidence: 0.98,
    extractionMethod: "inline_label",
    sourcePage: 1,
    sourceSnippet: "Adjusted EBITDA: $9.8M",
    sourceFile: "Northwind_Logistics_Q4_2025_Board_Pack.pdf",
  },
  {
    company: "Northwind Logistics",
    reportingPeriod: "Q4 2025",
    metricKey: "gross_margin",
    metricName: "Gross margin",
    category: "financial",
    rawValue: "61.4%",
    normalizedValue: 61.4,
    unit: "percent",
    confidence: 0.98,
    extractionMethod: "inline_label",
    sourcePage: 1,
    sourceSnippet: "Gross margin: 61.4%",
    sourceFile: "Northwind_Logistics_Q4_2025_Board_Pack.pdf",
  },
  {
    company: "Northwind Logistics",
    reportingPeriod: "Q4 2025",
    metricKey: "headcount",
    metricName: "Headcount",
    category: "operating",
    rawValue: "286 FTE",
    normalizedValue: 286,
    unit: "count",
    confidence: 0.98,
    extractionMethod: "inline_label",
    sourcePage: 1,
    sourceSnippet: "Headcount: 286 FTE",
    sourceFile: "Northwind_Logistics_Q4_2025_Board_Pack.pdf",
  },
  {
    company: "Northwind Logistics",
    reportingPeriod: "Q4 2025",
    metricKey: "nrr",
    metricName: "Net revenue retention",
    category: "operating",
    rawValue: "112%",
    normalizedValue: 112,
    unit: "percent",
    confidence: 0.98,
    extractionMethod: "inline_label",
    sourcePage: 1,
    sourceSnippet: "Net revenue retention: 112%",
    sourceFile: "Northwind_Logistics_Q4_2025_Board_Pack.pdf",
  },
  {
    company: "Northwind Logistics",
    reportingPeriod: "Q4 2025",
    metricKey: "pipeline",
    metricName: "Sales pipeline",
    category: "operating",
    rawValue: "$19.5M",
    normalizedValue: 19500000,
    unit: "USD",
    confidence: 0.98,
    extractionMethod: "inline_label",
    sourcePage: 1,
    sourceSnippet: "Qualified pipeline: $19.5M",
    sourceFile: "Northwind_Logistics_Q4_2025_Board_Pack.pdf",
  },
  {
    company: "Northwind Logistics",
    reportingPeriod: "Q4 2025",
    metricKey: "revenue",
    metricName: "Revenue",
    category: "financial",
    rawValue: "$48.2M",
    normalizedValue: 48200000,
    unit: "USD",
    confidence: 0.98,
    extractionMethod: "inline_label",
    sourcePage: 1,
    sourceSnippet: "Revenue: $48.2M",
    sourceFile: "Northwind_Logistics_Q4_2025_Board_Pack.pdf",
  },
];

export const METRIC_CATALOG = [
  { key: "revenue", label: "Revenue" },
  { key: "arr", label: "ARR" },
  { key: "ebitda", label: "EBITDA" },
  { key: "gross_margin", label: "Gross margin" },
  { key: "churn", label: "Churn" },
  { key: "nrr", label: "NRR" },
  { key: "headcount", label: "Headcount" },
  { key: "cash", label: "Cash" },
  { key: "pipeline", label: "Pipeline" },
] as const;

export const GITHUB_POC_URL =
  "https://github.com/ruthcokolo/sagard-portfolio-metrics";
